import { Inter, Montserrat } from 'next/font/google';
import './globals.css';

import { AppContextProvider } from '@/app/contexts/AppContext';
import Navbar from '@/app/components/Navbar';
import Footer from '@/app/components/Footer';

const inter = Inter({ subsets: ['latin'], variable:'--font-inter' });
const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-montserrat' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} ${montserrat.variable}`}>
        <AppContextProvider>
          <Navbar />
          {children}
          <Footer/>
        </AppContextProvider>
      </body>
    </html>
  );
}
