import { Inter, Montserrat } from 'next/font/google';
import './globals.css';

import { AppContextProvider } from '@/app/contexts/AppContext';
import Navbar from '@/app/components/Navbar';
import Footer from '@/app/components/Footer';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-montserrat' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      {/* min-h-screen y flex para asegurar que el footer quede abajo */}
      <body className={`${inter.variable} ${montserrat.variable} min-h-screen flex flex-col`}>
        <AppContextProvider>
          {/* Navbar se coloca arriba */}
          <Navbar />
          
          {/* flex-grow en el main para expandir el contenido y empujar el footer */}
          <main className="flex-grow">
            {children}
          </main>
          
          {/* Footer siempre estará al final */}
          <Footer />
        </AppContextProvider>
      </body>
    </html>
  );
}
